### ISSUE TITLE
1234

### ISSUE THREAD

**Issue by huliad2022** [kirbyloco/LineTV-DL#1]
55552

**Comment by kirbyloco** [comment]
@ali617768987 
剛測試了一下，是沒有問題的，
可以說明您是怎麼使用的嗎？

另外如果是最後出現object的話，
可以去看一下資料夾有沒有出現影片喔!

**Comment by huliad2022** [comment]
![20210125104821](https://user-images.githubusercontent.com/77323405/105655370-e7e03e80-5efa-11eb-8485-ecd5e17d3a3a.png)
是不是我操作有問題，這樣操作只能下載到字幕文件 資料夾裡面可以看到的只有字幕文件~ 求指教~

**Comment by kirbyloco** [comment]
@ali617768987 
OK，我晚點再測試一次。
另外想請問有無安裝ffmpeg呢?

**Comment by huliad2022** [comment]
> @ali617768987
> OK，我晚點再測試一次。
> 另外想請問有無安裝ffmpeg呢?

![微信截图_20210125153549](https://user-images.githubusercontent.com/77323405/105674842-1114c500-5f23-11eb-95a2-883e7ace7e1f.png)
我有把ffmpeg單獨複製到這個資料架裡面 不知道是不是這個原因 還是需要另外安裝？

**Comment by kirbyloco** [comment]
@ali617768987 
我剛剛有推送新的版本，
有檢查有沒有ffmpeg的功能，
可以試試看。

**Comment by huliad2022** [comment]
> @ali617768987
> 我剛剛有推送新的版本，
> 有檢查有沒有ffmpeg的功能，
> 可以試試看。

![1213](https://user-images.githubusercontent.com/77323405/105675692-6d2c1900-5f24-11eb-8b94-4a84c2b7f2cb.png)
我剛剛試了推送的新版本  這個應該是沒有ffmpeg的功能對吧 想問一下 我該怎麼裝 ffmpeg呢？

**Comment by kirbyloco** [comment]
@ali617768987 
這樣是有找到ffmpeg的
您可以嘗試看看下面的連結
https://www.linetv.tw/api/part/11781/eps/1/part
看有無報錯並截圖給我

若無報錯麻煩您將程式修改
![image](https://user-images.githubusercontent.com/17351171/105676484-8c777600-5f25-11eb-9a91-052d39c97d87.png)
把上圖框選出來的部分刪除

再麻煩您了

**Comment by huliad2022** [comment]
> @ali617768987
> 您可以嘗試看看下面的連結
> https://www.linetv.tw/api/part/11781/eps/1/part
> 看有無報錯並截圖給我
> 
> 若無報錯麻煩您將程式修改
> ![image](https://user-images.githubusercontent.com/17351171/105676484-8c777600-5f25-11eb-9a91-052d39c97d87.png)
> 把上圖框選出來的部分刪除
> 
> 再麻煩您了

![54555555](https://user-images.githubusercontent.com/77323405/105676870-158ead00-5f26-11eb-9982-78bd0bd685a8.png)

我打開鏈接顯示的是這個 然後 下載也是顯示這個

![1111111111111111](https://user-images.githubusercontent.com/77323405/105677126-728a6300-5f26-11eb-83d2-969be4f9dbb3.png)

**Comment by kirbyloco** [comment]
@ali617768987 
嘗試用用看我使用的ffmpeg版本
https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-4.3.1-2021-01-01-full_build.7z

**Comment by huliad2022** [comment]
> @ali617768987
> 嘗試用用看我使用的ffmpeg版本
> https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-4.3.1-2021-01-01-full_build.7z

![啊啊啊啊](https://user-images.githubusercontent.com/77323405/105680362-92238a80-5f2a-11eb-8c54-4ae3dc518f2b.png)
![bbb](https://user-images.githubusercontent.com/77323405/105680370-96e83e80-5f2a-11eb-8aa2-b940fa7afe8e.png)
我已經重新安裝了一下你給我發的FFmpeg的版本 但是還是這個樣子 嗚嗚嗚嗚

**Comment by kirbyloco** [comment]
我打包了m3u8和key檔案
[GitHub.zip](https://github.com/kirbyloco/LineTV-DL/files/5865275/GitHub.zip)
請解壓並在cmd輸入下面的指令
```ffmpeg -allowed_extensions ALL -protocol_whitelist file,http,https,tcp,tls,crypto -y -i 11507-eps-1_1080p.m3u8 -c copy KAIROS：化時為機-E1.mp4```

**Comment by huliad2022** [comment]
![微信截图_20210125165437](https://user-images.githubusercontent.com/77323405/105682961-0ad81600-5f2e-11eb-91ea-95bb1ac4861b.png)
輸入指令後是這樣的

**Comment by kirbyloco** [comment]
@ali617768987 
再試試看這串指令
```ffmpeg -allowed_extensions ALL -protocol_whitelist http,https,tls,rtp,tcp,udp,crypto,httpproxy,file -y -i 11507-eps-1_1080p.m3u8 -c copy KAIROS：化時為機-E1.mp4```

**Comment by huliad2022** [comment]
> @ali617768987
> 再試試看這串指令
> `ffmpeg -allowed_extensions ALL -protocol_whitelist http,https,tls,rtp,tcp,udp,crypto,httpproxy,file -y -i 11507-eps-1_1080p.m3u8 -c copy KAIROS：化時為機-E1.mp4`

用這個指令可以下 下成功了

**Comment by kirbyloco** [comment]
@ali617768987 
OK了解，感謝您幫忙測試，
我已經發布修正後的版本。

**Comment by huliad2022** [comment]
> @ali617768987
> OK了解，感謝您幫忙測試，
> 我已經發布修正後的版本。

不用客氣 還要感謝你分享了那麼好的工具 (づ￣ 3￣)づ
