### ISSUE TITLE
下載花絮

### ISSUE THREAD

**Issue by MyGoodbye** [kirbyloco/LineTV-DL#10]
花絮怎麼下載呢，集數怎麼填寫

**Comment by kirbyloco** [comment]
@MyGoodbye
目前花絮沒有辦法下載，
但有找到相關方法，
預計這兩天會處理好，
順便改寫一下Code。

**Comment by kirbyloco** [comment]
@MyGoodbye 
已經用好了，麻煩您測試一下。

**Comment by MyGoodbye** [comment]
好的。謝謝

在 2021年5月21日週五 06:32，耀風 ***@***.***> 寫道：

**Comment by MyGoodbye** [comment]
![image](https://user-images.githubusercontent.com/44659435/119070633-f955d500-ba1a-11eb-8d5a-8d7593a9b618.png)
是這樣用嗎？只下了一個字幕

**Comment by kirbyloco** [comment]
@MyGoodbye 
```Linetv.DL.Behind(Linetv.Parser('影集ID').behind())```
可以用用看這個方法，
之後會簡化方法的

**Comment by MyGoodbye** [comment]
![image](https://user-images.githubusercontent.com/44659435/119076407-142d4700-ba25-11eb-8ba0-b99aad80f1a1.png)
報錯了

**Comment by kirbyloco** [comment]
@MyGoodbye 
後面的behind裡面不需要填入參數

**Comment by MyGoodbye** [comment]
好了，謝謝

**Comment by MyGoodbye** [comment]
問一個問題，花絮可以視頻帶幕，下載影片怎麼字幕是分開的呢？

**Comment by kirbyloco** [comment]
@MyGoodbye 
在Linetv的影集大部分是分開的（像Netflix一樣），
只有少部分是內嵌，
而花絮基本上都是內嵌的

**Comment by MyGoodbye** [comment]
好的，謝謝～~
