### ISSUE TITLE
無法執行

### ISSUE THREAD

**Issue by cosmos5732** [kirbyloco/LineTV-DL#12]
請問透過python執行後出現錯誤訊息，如下
Traceback (most recent call last):
  File "D:\LineTV-Dowlond\LineTV-DL-master\Linetv.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

是執行方式有什麼問題嗎

**Comment by kirbyloco** [comment]
@cosmos5732 
請先執行```pip install -r requirements.txt```

再依照readme的方式執行

**Comment by cosmos5732** [comment]
成功執行了，謝謝

**Comment by cosmos5732** [comment]
不好意思想請問，影片下載後，分開的字幕有什麼方式可以合併影片一起播放

**Comment by cosmos5732** [comment]
不好意思想請問，影片成功下載後，分開的字幕有什麼方式可以合併影片一起播放，試過很多種方式，不管是不同播放器還是透過第三方軟體合併，都無法成功將字幕加入影片

**Comment by kirbyloco** [comment]
@cosmos5732 
簡單的方法就使用mkvtoolmix合併即可
如果要內嵌就要用ffmpeg或其他工具了

**Comment by cosmos5732** [comment]
有試過使用MKVToolNix合併，但是依舊無法成功

**Comment by kirbyloco** [comment]
@cosmos5732 
請問是用甚麼播放器??
我用Potplayer測試正常

**Comment by cosmos5732** [comment]
我用win10內建的電影與電視，他有可以選擇字幕，但是字幕怎麼選擇就是顯示不出來
內建的Windows Media Player也是無法選擇字幕
有另外下載VLC Media Player要開啟字幕則是顯示讀取有問題
我也有試過把字幕檔.vtt改為.srt，也還是無法顯示

**Comment by kirbyloco** [comment]
@cosmos5732 
電影與電視和Windows Media Player基本上無法播放srt和vtt串流平台的字幕，
另外vtt和srt的格式不同，不能使用改附檔名的方式解決，
至於VLC Media Player我確定SRT是正常的，
vtt就不確定了。

**Comment by cosmos5732** [comment]
謝謝你的回覆
我直接下載Potplayer播放器，可以成功顯示字幕了
不過想請問MKVToolNix無法成功合併字幕，有什麼原因會造成嗎
按造網路上的教學，試過很多次不斷重新合併，打開的檔案就是沒有字幕
