### ISSUE TITLE
會員

### ISSUE THREAD

**Issue by MyGoodbye** [kirbyloco/LineTV-DL#13]
能問一下目前會員下載進展到哪裏了嗎？

**Comment by kirbyloco** [comment]
@MyGoodbye 
這陣子在忙考試的事，
等考完就會更新。

**Comment by MyGoodbye** [comment]
okay，謝謝

在 2021年6月23日週三 08:51，耀風 ***@***.***> 寫道：

**Comment by kirbyloco** [comment]
@MyGoodbye 
我有嘗試加入了登入的功能，
麻煩試試看。

另外登入功能可能會難產，
由於LineTV的登入畫面大部分是JS渲染出來的，
Python不太好在這方面做處理。

**Comment by MyGoodbye** [comment]
好的，等下試

在 2021年6月25日週五 09:14，耀風 ***@***.***> 寫道：

**Comment by MyGoodbye** [comment]
我重新fork了一份你的新代碼，也改名填好access token，但是
![image](https://user-images.githubusercontent.com/44659435/123362366-23169480-d5a3-11eb-986d-0617188ac2ce.png)
我用npm  install import，但是
![image](https://user-images.githubusercontent.com/44659435/123362440-417c9000-d5a3-11eb-9b1f-c71f59c7a487.png)

**Comment by kirbyloco** [comment]
@MyGoodbye 
阿...這是python的專案阿
先進python再輸入import Linetv

**Comment by MyGoodbye** [comment]
哦，忘了。。

**Comment by MyGoodbye** [comment]
![image](https://user-images.githubusercontent.com/44659435/123363008-3f670100-d5a4-11eb-99aa-8720b918d2f5.png)
這個是？

**Comment by kirbyloco** [comment]
@MyGoodbye 
我嘗試下載是沒有問題的

**Comment by MyGoodbye** [comment]
只填access token，refresh token不填對吧

在 2021年6月25日週五 11:16，耀風 ***@***.***> 寫道：

**Comment by kirbyloco** [comment]
@MyGoodbye 
對的

**Comment by MyGoodbye** [comment]
那我再試下

**Comment by MyGoodbye** [comment]
還是不行，非會員都不行了

**Comment by kirbyloco** [comment]
@MyGoodbye 
我會員(非VIP)和非會員都可行，
嘗試看看回復到上個commit看可不可以。

**Comment by MyGoodbye** [comment]
好

在 2021年6月25日週五 11:35，耀風 ***@***.***> 寫道：

**Comment by MyGoodbye** [comment]
我回退之前是可以下的，但fork最新不行
![image](https://user-images.githubusercontent.com/44659435/123381412-49e4c300-d5c3-11eb-96bd-fd2f9955ad0e.png)
這是回退的文件，你最新github是缺文件嗎，我直接拉取可以嗎

**Comment by kirbyloco** [comment]
@MyGoodbye 
那個不是缺文件，
但這次的commit我只有增加代碼，
應該不會影響到下載的部分，
我會再修改看看。

**Comment by MyGoodbye** [comment]
好的，後續再測試

**Comment by MyGoodbye** [comment]
![image](https://user-images.githubusercontent.com/44659435/123530340-9fd47a80-d72b-11eb-8771-8b37c6da7380.png)
我重新拉取了最新的，還是不行，你看我這里少了什麼嗎？

**Comment by kirbyloco** [comment]
@MyGoodbye 
我有找到問題點了，
主要是解密的key授權失敗。

**Comment by MyGoodbye** [comment]
那我需要改什麼呢？

**Comment by kirbyloco** [comment]
@MyGoodbye 
我已經推送新的commit，
麻煩在測試看看。

**Comment by MyGoodbye** [comment]
可以了。謝謝

**Comment by Musselmarss** [comment]
我遇到一個問題, 他下載了.vtt 字幕file, 但裡面是寫著<Error><Code>InvalidArgument</Code><Message>Authorization header is invalid -- one and only one ' ' (space) required</Message><ArgumentName>Authorization</ArgumentName><ArgumentValue>

請問出了什麼問題? 謝謝。

**Comment by kirbyloco** [comment]
@Musselmarss 請到 #15 進行討論

**Comment by Musselmarss** [comment]
謝謝!
