### ISSUE TITLE
字幕檔下載有問題

### ISSUE THREAD

**Issue by GaryZong** [kirbyloco/LineTV-DL#15]
下載後以下錯誤呈現錯誤
![vtt ERROR](https://user-images.githubusercontent.com/22173503/130266298-ea40d835-c5ab-4f30-b921-d1216ab5487b.PNG)

**Comment by kirbyloco** [comment]
@gary66323 
目前看來Linetv又改規則了，
導致之前的字幕下載規則錯誤，
但下載新劇的字幕是沒有問題的，

我會改成先嘗試新的下載方式，
失敗的話改成舊的方式。

**Comment by kirbyloco** [comment]
@gary66323 
麻煩你再試試看。

**Comment by Musselmarss** [comment]
謝謝! 現在我再試試

**Comment by Musselmarss** [comment]
剛剛試過 .vtt file沒了, 但片中也沒有字幕. 可以再看看嗎? 謝謝你

**Comment by GaryZong** [comment]
@kirbyloco 
可以了謝謝

但是在敘述中並未提到下載字幕方法，希望可以在『readme』檔中做說明

法1  (此方法為《未修改》程式碼)
若要《手動》下載字幕時需要注意的地方
原：Linetv.DL.Drama('輸入影集的ID', '影集的集數') 
改：Linetv.DL.Drama('輸入影集的ID', '影集的集數','True') 

使用方式 『需要下載字幕』：
import Linetv
Linetv.DL.Drama('輸入影集的ID', '影集的集數','True') 

使用方式 『無需下載字幕』：
import Linetv
Linetv.DL.Drama('輸入影集的ID', '影集的集數') 

================================================

法2  (此方為《修改》程式碼)
若要《自動》下載字幕需修改『Linetv.py』檔的『第55行』才會自動下載字幕
原：def __init__(self, dramaid: str, ep: str, subtitle=False):
改：def __init__(self, dramaid: str, ep: str, subtitle=true):

使用方式 『需要下載字幕』：
import Linetv
Linetv.DL.Drama('輸入影集的ID', '影集的集數') 

使用方式 『無需下載字幕』：
import Linetv
Linetv.DL.Drama('輸入影集的ID', '影集的集數','False')

**Comment by kirbyloco** [comment]
@Musselmarss 
請麻煩提供DramaID，畢竟不一定每部劇都會有外掛字幕。

@GaryZong 
關於這點主要是我要改用命令行的方式，
所以預設就不會自動下載字幕了，
開發者的方式就留給其他需要的人了。

**Comment by Musselmarss** [comment]
@kirbyloco @GaryZong 
謝謝你們的幫助, 剛試了 下載成功.

**Comment by yinmo-public** [comment]
剛剛下載完斯卡羅了 謝謝~

**Comment by GaryZong** [comment]
@kirbyloco 
我有測試過若修改程式碼的『第55行』『subtitle=False』改為『subtitle=True』是不影響字幕下載，雖然有些影片是無字幕但是它會自動辨識是否有字幕可下載
而修改後只在CMD中輸入『python Linetv.py --dramaid <Dramaid> --ep <集數>』
以下是我修改程式碼後下載執行的結果分別為有 外掛字幕 以及 無外掛字幕
![修改](https://user-images.githubusercontent.com/22173503/130324857-b8ef147b-604b-416f-89b0-30689ffc2cc8.png)

**Comment by kirbyloco** [comment]
@GaryZong 
那我後續改成優先自動下載字幕，
改成可以手動關閉字幕。

**Comment by GaryZong** [comment]
@kirbyloco 
我這裡有簡化過的下載方式不知你是否需要參考看看

```
@echooff
title LineTV下載器
:begin
echo.======================================
echo.          ※LineTV下載器※
echo.======================================
echo.請輸入需要下載的影片代碼：
set /p sn=
echo.
echo.請輸入需要下載的集數：
set /p ep=
echo.
echo.======================================
echo.            ※下載進度※
echo.======================================
echo.
python Linetv.py --dramaid %sn% --ep %ep%
echo.
set /p menu="請問是否要繼續下載影片 ? (Y/N):"
if %menu%==Y goto Yes
if %menu%==y goto Yes
if %menu%==N goto No
if %menu%==n goto No
:Yes
cls
goto :begin
:No
exit
```
![CMD](https://user-images.githubusercontent.com/22173503/130328949-ba79429c-5d29-491a-8cbb-2db11a6171b9.PNG)

**Comment by kirbyloco** [comment]
@GaryZong 
這種的話我覺得相當多餘，
我相信會裝python和來逛Github的，
都是有資訊和資工底子的人了。

但有時間我還是會把這東西直接整合，
不需要使用bat處理。
