### ISSUE TITLE
可能是vpn的原因

### ISSUE THREAD

**Issue by yuki1004** [kirbyloco/LineTV-DL#16]
报错
raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.linetv.tw', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1129)')))
试了网上的各种办法，请问有办法解决嘛--！
好的解决了，谢谢你这么好的东西！

**Comment by kirbyloco** [comment]
謝謝你的支持
