### ISSUE TITLE
下載失敗

### ISSUE THREAD

**Issue by Railgun555** [kirbyloco/LineTV-DL#17]
python新手，想請教一下“下載失敗”的原因和解決方法。謝謝

![B384DCE6-DFB8-4036-A090-53EA68131DDF](https://user-images.githubusercontent.com/100003101/154778536-73191f2c-0f27-44a0-8d4f-667247049476.png)

**Comment by kirbyloco** [comment]
@Railgun555 
請確認資料夾是否有多出m3u8和key的檔案。

**Comment by Railgun555** [comment]
> @Railgun555
> 請確認資料夾是否有多出m3u8和key的檔案。

資料夾確實有多出的m3u8和key檔案，但是刪掉之後依然提示“下載失敗”

![B5E6EED3-B36D-46BF-AAB2-0A678CE37F47](https://user-images.githubusercontent.com/100003101/154785254-b9be5178-1194-49bd-bc16-89a30336b037.jpeg)
![C9402057-254A-4CFF-820C-3E1933DCC619](https://user-images.githubusercontent.com/100003101/154785101-a0150838-eded-461d-84e4-027ee6b5ba16.jpeg)
![D9A65E4D-B0C2-4432-8DEB-86F8C1DB4CB7](https://user-images.githubusercontent.com/100003101/154785266-bee75d74-282e-41ab-8c29-1e4543a1269a.png)

**Comment by kirbyloco** [comment]
@Railgun555 
確認一下使用記事本等軟體打開m3u8檔案，是否長得像這樣
```
#EXTM3U
#EXT-X-VERSION:4
#EXT-X-TARGETDURATION:10
#EXT-X-MEDIA-SEQUENCE:1
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-KEY:METHOD=AES-128,URI="12516-eps-1_1080p.key",IV=0x00000000000000000000000000000001
#EXTINF:10,
#EXT-X-BYTERANGE:8090960@0
https://d3c7rimkq79yfu.cloudfront.net/12516/1/v2/1080/12516-eps-1_1080p.ts
#EXT-X-KEY:METHOD=AES-128,URI="12516-eps-1_1080p.key",IV=0x00000000000000000000000000000002
```
是的話，嘗試用下面這條指令，
```
ffmpeg -i .\12516-eps-1_1080p.m3u8 -movflags +faststart -c copy 刑偵日記-E1.mp4
```

**Comment by Railgun555** [comment]
> @Railgun555 確認一下使用記事本等軟體打開m3u8檔案，是否長得像這樣
> 
> ```
> #EXTM3U
> #EXT-X-VERSION:4
> #EXT-X-TARGETDURATION:10
> #EXT-X-MEDIA-SEQUENCE:1
> #EXT-X-PLAYLIST-TYPE:VOD
> #EXT-X-KEY:METHOD=AES-128,URI="12516-eps-1_1080p.key",IV=0x00000000000000000000000000000001
> #EXTINF:10,
> #EXT-X-BYTERANGE:8090960@0
> https://d3c7rimkq79yfu.cloudfront.net/12516/1/v2/1080/12516-eps-1_1080p.ts
> #EXT-X-KEY:METHOD=AES-128,URI="12516-eps-1_1080p.key",IV=0x00000000000000000000000000000002
> ```
> 
> 是的話，嘗試用下面這條指令，
> 
> ```
> ffmpeg -i .\12516-eps-1_1080p.m3u8 -movflags +faststart -c copy 刑偵日記-E1.mp4
> ```

m3u8檔案打開後以上述內容一致，嘗試這條指令後，提示如下圖：
![784CB458-FBD9-4B60-8FE7-AF4C71B12546](https://user-images.githubusercontent.com/100003101/154796544-89e0093d-f0df-464d-b61d-ce18880a072b.png)

![31A85C30-0E9B-4840-8276-58392A893AD8](https://user-images.githubusercontent.com/100003101/154796554-e508a028-ac92-43ca-a2a4-cdd0ce296d39.png)

資料夾的檔案沒有變化
![BC0ED9C3-C09D-4FC1-92A5-E4DEAAB93372](https://user-images.githubusercontent.com/100003101/154796804-6a9d5af8-9bda-433b-92c5-4f5652761d0b.jpeg)

key用記事本打開的話是這樣的
![EED6FD23-151E-44D6-AF65-F4D15D0D395D](https://user-images.githubusercontent.com/100003101/154796773-16266dac-10af-4fef-b149-8b906b845be3.jpeg)

**Comment by kirbyloco** [comment]
@Railgun555 
請改用這條指令
```
ffmpeg -allowed_extensions ALL -protocol_whitelist http,https,tls,rtp,tcp,udp,crypto,httpproxy,file -y -i 12516-eps-1_1080p.m3u8 -movflags +faststart -c copy ./刑偵日記-E1.mp4
```

**Comment by Railgun555** [comment]
> @Railgun555 請改用這條指令
> 
> ```
> ffmpeg -allowed_extensions ALL -protocol_whitelist http,https,tls,rtp,tcp,udp,crypto,httpproxy,file -y -i 12516-eps-1_1080p.m3u8 -movflags +faststart -c copy ./刑偵日記-E1.mp4
> ```

無法打開key的錯誤沒有了，但是其他提示還是一樣
![7624035E-76CD-43B0-B67B-417F8C8DB00D](https://user-images.githubusercontent.com/100003101/154798252-2baffa59-d24e-46fd-ac88-57267308407d.png)

![2C8FA706-CDB3-463F-BE1E-64D738E620C9](https://user-images.githubusercontent.com/100003101/154798317-e25b5b80-ebc7-4b51-b7ec-c86a8b5551f4.png)

**Comment by kirbyloco** [comment]
@Railgun555 
嘗試直接在瀏覽器打開這個連結
```
https://d3c7rimkq79yfu.cloudfront.net/12516/1/v2/1080/12516-eps-1_1080p.ts
```
若可以順利下載，
請嘗試把ffmpeg更新。
https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full.7z

**Comment by Railgun555** [comment]
> @Railgun555 嘗試直接在瀏覽器打開這個連結
> 
> ```
> https://d3c7rimkq79yfu.cloudfront.net/12516/1/v2/1080/12516-eps-1_1080p.ts
> ```
> 
> 若可以順利下載， 請嘗試把ffmpeg更新。 https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full.7z

真的是ffmpeg的問題，可以下載了，非常感謝！
