### ISSUE TITLE
importing

### ISSUE THREAD

**Issue by Rule1311** [kirbyloco/LineTV-DL#2]
I am getting " no such file or directory"  when i try to import linetv.

**Comment by kirbyloco** [comment]
@Rule1311 
please follow step:
```
In Windows 10
1. Download "Linetv.py" to folder
2. Use Shift+Right Click and Click Powershell or CMD in the folder
3. type python
4. follow README step
```

so this cant resolve the problem??

**Comment by kirbyloco** [comment]
@Rule1311 
Can you take a screenshot?

**Comment by Rule1311** [comment]
i did the following
1. Download "Linetv.py" to folder
2. Use Shift+Right Click and Click Powershell or CMD in the folder
3. type python
![2021-02-24_051833](https://user-images.githubusercontent.com/79296967/108986115-cbe9cd00-765f-11eb-881a-f352f8863719.png)

**Comment by kirbyloco** [comment]
@Rule1311 
You need to use Enter to next step
like this
1. type python and Enter
2. type import Linetv and Enter

**Comment by Rule1311** [comment]
I did that too, nothing happens after enter "import Linetv" see the screenshot.

![import](https://user-images.githubusercontent.com/79296967/108989678-dc03ab80-7663-11eb-85d0-97b9da254119.png)

**Comment by kirbyloco** [comment]
> I did that too, nothing happens after enter "import Linetv" see the screenshot.
> 
> ![import](https://user-images.githubusercontent.com/79296967/108989678-dc03ab80-7663-11eb-85d0-97b9da254119.png)

it's right.
and use Linetv.DL(drama id, ep number)

**Comment by Rule1311** [comment]
I was expecting something to happen after "import Linetv"
thank you very much for your help.
