### ISSUE TITLE
免登入、免VIP直接下載1080p 真的很需要啊大佬😭考虑回归这个功能么还…😭😭呜呜呜呜

### ISSUE THREAD

**Issue by artemisluck97** [kirbyloco/LineTV-DL#27]
**發布此Issue前請先確定**
1. 版本為最新版
2. 是否已安裝相關套件

**電腦環境**
Python版本：
FFmpeg版本：
是否有使用VPN：

**問題敘述**

**錯誤截圖**

**錯誤Log檔**

**Comment by artemisluck97** [comment]
免登入、免VIP直接下載1080p （已於2022/03/29失效）（有方法應對但估計不會公開）
就是想问一下👆🏻这个功能还能回归吗…很需要这个功能😭😭😭

**Comment by kirbyloco** [comment]
會這麼說就代表，
我認為 Line TV 官方已經注意到這個 Repo，
所以繞過限制的功能就不會去修復，
強烈建議上 VIP 會員也會比較省心。
