### ISSUE TITLE
请问字幕可以选择srt格式的吗？下载下来是vtt的

### ISSUE THREAD

**Issue by artemisluck97** [kirbyloco/LineTV-DL#31]
**發布此Issue前請先確定**
1. 版本為最新版
2. 是否已安裝相關套件

**電腦環境**
Python版本：
FFmpeg版本：
是否有使用VPN：

**問題敘述**

**錯誤截圖**

**錯誤Log檔**

**Comment by kirbyloco** [comment]
已新增該功能。
