### ISSUE TITLE
大佬是不是又有更新了

### ISSUE THREAD

**Issue by baobeiboboda** [kirbyloco/LineTV-DL#33]
<img width="565" alt="image" src="https://user-images.githubusercontent.com/12625368/189497300-e3a50fde-8f16-4745-b9a3-f91a42da7421.png">

应该是ffmpeg的相关问题 但是我ffmpeg 是可以正常运行的

<img width="579" alt="image" src="https://user-images.githubusercontent.com/12625368/189497336-0958cd08-7d90-4604-a888-72adfbef441f.png">

请问 哪里出现问题 导致这个错误出现

**Comment by kirbyloco** [comment]
@baobeiboboda 
已修正，麻煩在測試看看。

**Comment by Musselmarss** [comment]
當我下載完就出了下面message, 而且每一集都分了三個files, 可以問一下什麼問題嗎? 謝謝
![Screenshot 2023-01-14 233319](https://user-images.githubusercontent.com/79889041/212467748-52ae96e7-f358-45af-b08c-5c556e57cb4a.png)
