### ISSUE TITLE
123456

### ISSUE THREAD

**Issue by huliad2022** [kirbyloco/LineTV-DL#4]
123456

**Comment by kirbyloco** [comment]
@ali617768987 
像KKTV的檔案有用DRM加密保護，基本上就只能透過錄影的方式解決，
不過也有人去修改Chrome瀏覽器來繞過DRM加密。
Friday影音我就沒有碰過了。

**Comment by huliad2022** [comment]
> @ali617768987
> 像KKTV的檔案有用DRM加密保護，基本上就只能透過錄影的方式解決，
> 不過也有人去修改Chrome瀏覽器來繞過DRM加密。
> Friday影音我就沒有碰過了。

好的，謝謝解答，應該會很麻煩吧
