### ISSUE TITLE
How to get Chinese subtitle?

### ISSUE THREAD

**Issue by alandai28** [kirbyloco/LineTV-DL#5]
你好，我試著下載影片11976時，出現這個log
  File "C:\Users\aland\Desktop\LineTV-DL-master\Linetv.py", line 111, in dl_video
    f.write(sub.text)
UnicodeEncodeError: 'cp950' codec can't encode character '\u70bb' in position 23246: illegal multibyte sequence

我試著把程式改成
f.write(sub.text.encode("utf8").decode("cp950", "ignore"))
跑是跑過了，可是存出來的vtt檔，裡面的字幕是任何編碼都無法正確顯示的亂碼，只有時間軸是看得懂的
不知道您有沒有什麼看法?

**Comment by renwokuang** [comment]
怎样用命令行下载的

**Comment by alandai28** [comment]
def main():
	drama_id = '11976'
	Parser(drama_id)
	DL(drama_id, '1')

if __name__ == '__main__': 
    main()
我發現不是每集都這樣，3.4集是正常的，也許是字幕的內容有問題
後來我把字幕在終端機印出來
print(sub.text)
自己在複製貼成檔案...

另外請問您有做過line tv登入的code嗎?

**Comment by kirbyloco** [comment]
@alandai28 
現在身邊沒有電腦可以測試，
等連假結束後我再試試看。

@renwokuang 
命令行的使用方法我有打在readme

**Comment by kirbyloco** [comment]
@alandai28 
我嘗試修正了編碼的問題，再麻煩您試試看，
另外你提到的登入Code目前是沒有做（主要是因為我沒有LineTV的會員可以測試）

**Comment by alandai28** [comment]
@kirbyloco 
感謝，看起來沒問題囉

**Comment by renwokuang** [comment]
不会用这个命令行

**Comment by kirbyloco** [comment]
@renwokuang 
因為這不太算是命令行
而是python引入模塊的方法
可以參考 #2 的操作
