### ISSUE TITLE
想詢問執行出現錯誤

### ISSUE THREAD

**Issue by imkent02** [kirbyloco/LineTV-DL#7]
python新手,想詢問執行的錯誤要怎麼處理?謝謝
![擷取](https://user-images.githubusercontent.com/82456682/114564314-cb0a0a80-9ca2-11eb-84e2-c1fd9173af1b.PNG)

**Comment by kirbyloco** [comment]
@imkent02 
先安裝必要的套件，
在CMD輸入
```
pip3 install requests
pip3 install lxml
```

**Comment by imkent02** [comment]
謝謝!已執行成功,想問VIP功能是不是失效 
>>> Linetv.DL('11869', '1')
無法觀看VIP獨享內容。
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\NEKO\Documents\LineTV-DL-master\Linetv.py", line 45, in __init__
    self.get_m3u8_key()
  File "C:\Users\NEKO\Documents\LineTV-DL-master\Linetv.py", line 78, in get_m3u8_key
    token = req.json()['token']
KeyError: 'token'

**Comment by kirbyloco** [comment]
@imkent02 
"免登入、VIP直接下載1080p"指的是不用登入和VIP就可以下載1080P的，
不可以跳過VIP限定的影片。

**Comment by MyGoodbye** [comment]
![image](https://user-images.githubusercontent.com/44659435/117523878-408ca080-afed-11eb-814a-23e4a228d063.png)
输入pip3 install requests
pip3 install lxml
报错
