### ISSUE TITLE
下载第二集有问题,其他都可以，是什么原因？

### ISSUE THREAD

**Issue by Cool-Loong** [kirbyloco/LineTV-DL#8]
下载第二集就一个预告，一分多钟，其他的集数下载都是完整的

**Comment by kirbyloco** [comment]
@Cool-Loong 
能提供id讓我測試嗎？

**Comment by Cool-Loong** [comment]
Linetv.DL('9073', 1)

**Comment by Cool-Loong** [comment]
上次那个问题是我的网络问题，上面这个id下载失败

**Comment by kirbyloco** [comment]
@Cool-Loong 
稍微檢查一下，
該劇在LineTV沒有720P以上的畫質導致失敗，
而且這部的m3u8檔案命名規則也不同，

我這裡建議去Youtube直接用youtube-dl下載，
該劇在YT有Linetv上傳的1080p的版本
[YT連結](https://www.youtube.com/watch?v=OnCD6xSzUP8)

**Comment by Cool-Loong** [comment]
好的，感谢
