### ISSUE TITLE
会员影片

### ISSUE THREAD

**Issue by MyGoodbye** [kirbyloco/LineTV-DL#9]
有会员如何下载会员影片呢

**Comment by kirbyloco** [comment]
@MyGoodbye 
目前沒有登入和載入cookie的部分，
暫時無法下載。

**Comment by MyGoodbye** [comment]
什么时候可以支持会员下载吗

**Comment by MyGoodbye** [comment]
![image](https://user-images.githubusercontent.com/44659435/117524790-a418cd00-aff1-11eb-9821-1c82d96b4945.png)
還有這個是什麼原因呢？

**Comment by MyGoodbye** [comment]
![image](https://user-images.githubusercontent.com/44659435/117526148-b85ec900-aff5-11eb-98a9-31efb4ae1892.png)
安装解压了ffmpeg还是不行

**Comment by MyGoodbye** [comment]
![image](https://user-images.githubusercontent.com/44659435/117531748-b35e4180-b016-11eb-9cfa-5025211e9ba2.png)
最新問題，我有設置代理。

**Comment by kirbyloco** [comment]
@MyGoodbye 
會員登入有在做了，但由於比較複雜，
所以應該會先推出使用Cookie登入的方法解決，
下載的部分請使用台灣的代理，然後開啟全局模式。

**Comment by MyGoodbye** [comment]
對，我是台灣全局

**Comment by kirbyloco** [comment]
@MyGoodbye 
我測試過了12231這個ID，
這是LineTV那邊不開放給台灣觀看，
這就沒有辦法解決。

**Comment by MyGoodbye** [comment]
那估計我填錯ID了

在 2021年5月10日週一 下午4:26，耀風 ***@***.***> 寫道：

**Comment by MyGoodbye** [comment]
![image](https://user-images.githubusercontent.com/44659435/117639119-281bb200-b1b6-11eb-8241-b5f199420f36.png)
突然這樣了

**Comment by kirbyloco** [comment]
@MyGoodbye
就重新安裝lxml
```pip install lxml```

**Comment by MyGoodbye** [comment]
> @MyGoodbye
> 就重新安裝lxml
> ```pip install lxml```

好，謝謝

**Comment by MyGoodbye** [comment]
己弄好，謝謝。
